import { useState } from 'react';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Layout from '@/components/layout/Layout';
import WindowModel from '../models/window';
import 'bootstrap/dist/css/bootstrap.css';
import '../styles/globals.css';

export default function App({ Component, pageProps }: AppProps) {
  const windows = [
    new WindowModel(
      'Home',
      (
        <>
          <h1>Home</h1>
        </>
      ),
      'home-window',
      'home-btn'
    ),
    new WindowModel(
      'Products',
      (
        <>
          <h1>Products</h1>
        </>
      ),
      'products-window',
      'products-btn'
    ),
  ];
  const menuItems = [
    new WindowModel('Placeholder', <></>, '', ''),
    new WindowModel('Placeholder', <></>, '', ''),
    new WindowModel('Placeholder', <></>, '', ''),
  ];

  const [focusedWindow, setFocusedWindow] = useState<WindowModel>(windows[0]);

  return (
    <>
      <Head>
        <title>{`Retail Resale${pageProps.title ? ` - ${pageProps.title as string}` : ''}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <Layout
        windows={windows}
        focusedWindow={focusedWindow}
        setFocusedWindow={setFocusedWindow}
        menuItems={menuItems}
      >
        <Component {...pageProps} windows={windows} />
      </Layout>
    </>
  );
}
