import { useState } from 'react';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Layout from '../components/layout/Layout';
import StartBar from '../components/windows/start-bar/StartBar';
import Products from '../components/pages/Products';
import WindowModel from '../models/window';

import 'bootstrap/dist/css/bootstrap.css';
import '../styles/globals.css';

export default function App({ Component, pageProps }: AppProps) {
  const homeComponent = <Layout title="Home" content={<></>} />;
  const productsComponent = <Layout title="Products" content={<Products />} />;
  const windows = [
    new WindowModel('Home', homeComponent, 'home-window', 'home-btn'),
    new WindowModel('Products', productsComponent, 'products-window', 'products-btn'),
  ];
  const menuItems = [
    new WindowModel('Placeholder', <></>, '', ''),
    new WindowModel('Placeholder', <></>, '', ''),
    new WindowModel('Placeholder', <></>, '', ''),
  ];

  const [windowValue, setWindowValue] = useState<number>(0);

  const handleWindowChange = (event: React.SyntheticEvent, newValue: number) =>
    setWindowValue(newValue);

  return (
    <>
      <Head>
        <title>{`Retail Resale${pageProps.title ? ` - ${pageProps.title as string}` : ''}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <Component {...pageProps} windowValue={windowValue} windows={windows} />

      <StartBar
        windowValue={windowValue}
        windows={windows}
        handleChange={handleWindowChange}
        menuItems={menuItems}
      />
    </>
  );
}
